### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Philopateer2099** [Madhava213/Web-Dev-Framework-Setup#1]
i just downloaded it and tried running it and it just opens a terminal window and closes it and that's it?

**Comment by Madhava213** [comment]
> i just downloaded it and tried running it and it just opens a terminal window and closes it and that's it?

You should be seeing a locally running browser window opened in your default browser. The terminal is just for the application's runtime. All functionality is done in the browser window that is opened. Also, please make sure you have "streamlit" installed in your python environment. Let me know if you still cant run it.

**Comment by Philopateer2099** [comment]
> > i just downloaded it and tried running it and it just opens a terminal window and closes it and that's it?
> 
> You should be seeing a locally running browser window opened in your default browser. The terminal is just for the application's runtime. All functionality is done in the browser window that is opened. Also, please make sure you have "streamlit" installed in your python environment. Let me know if you still cant run it.

Ik I read the README but it doesn't open the browser when I click the runner.exe 

I am using windows and my device has python installed my default browser is edge

**Comment by Madhava213** [comment]
Sorry for the late reply..... 
The application runs on port **8501**. Please make sure your port is open. You can access the application at : **http://localhost:8501/** once you run **Runner.exe**.
